/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPlatformsRouteImport } from './routes/app.platforms'
import { Route as AppOutreachRouteImport } from './routes/app.outreach'
import { Route as AppHotlistRouteImport } from './routes/app.hotlist'
import { Route as AppExpansionRouteImport } from './routes/app.expansion'
import { Route as AppDiscoveryRouteImport } from './routes/app.discovery'
import { Route as AppCreatorsRouteImport } from './routes/app.creators'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppAffiliateRouteImport } from './routes/app.affiliate'
import { Route as AppCampaignsIndexRouteImport } from './routes/app.campaigns.index'
import { Route as AppCreatorsIdRouteImport } from './routes/app.creators.$id'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformsRoute = AppPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppHotlistRoute = AppHotlistRouteImport.update({
  id: '/hotlist',
  path: '/hotlist',
  getParentRoute: () => AppRoute,
} as any)
const AppExpansionRoute = AppExpansionRouteImport.update({
  id: '/expansion',
  path: '/expansion',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsRoute = AppCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCreatorsIdRoute = AppCreatorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCreatorsRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/community': typeof AppCommunityRoute
  '/app/creators': typeof AppCreatorsRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/expansion': typeof AppExpansionRoute
  '/app/hotlist': typeof AppHotlistRoute
  '/app/outreach': typeof AppOutreachRoute
  '/app/platforms': typeof AppPlatformsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/community': typeof AppCommunityRoute
  '/app/creators': typeof AppCreatorsRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/expansion': typeof AppExpansionRoute
  '/app/hotlist': typeof AppHotlistRoute
  '/app/outreach': typeof AppOutreachRoute
  '/app/platforms': typeof AppPlatformsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/community': typeof AppCommunityRoute
  '/app/creators': typeof AppCreatorsRouteWithChildren
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/expansion': typeof AppExpansionRoute
  '/app/hotlist': typeof AppHotlistRoute
  '/app/outreach': typeof AppOutreachRoute
  '/app/platforms': typeof AppPlatformsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/affiliate'
    | '/app/campaigns'
    | '/app/community'
    | '/app/creators'
    | '/app/discovery'
    | '/app/expansion'
    | '/app/hotlist'
    | '/app/outreach'
    | '/app/platforms'
    | '/app/settings'
    | '/invite/$token'
    | '/app/'
    | '/app/campaigns/$id'
    | '/app/creators/$id'
    | '/app/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/affiliate'
    | '/app/community'
    | '/app/creators'
    | '/app/discovery'
    | '/app/expansion'
    | '/app/hotlist'
    | '/app/outreach'
    | '/app/platforms'
    | '/app/settings'
    | '/invite/$token'
    | '/app'
    | '/app/campaigns/$id'
    | '/app/creators/$id'
    | '/app/campaigns'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/affiliate'
    | '/app/campaigns'
    | '/app/community'
    | '/app/creators'
    | '/app/discovery'
    | '/app/expansion'
    | '/app/hotlist'
    | '/app/outreach'
    | '/app/platforms'
    | '/app/settings'
    | '/invite/$token'
    | '/app/'
    | '/app/campaigns/$id'
    | '/app/creators/$id'
    | '/app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/platforms': {
      id: '/app/platforms'
      path: '/platforms'
      fullPath: '/app/platforms'
      preLoaderRoute: typeof AppPlatformsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outreach': {
      id: '/app/outreach'
      path: '/outreach'
      fullPath: '/app/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hotlist': {
      id: '/app/hotlist'
      path: '/hotlist'
      fullPath: '/app/hotlist'
      preLoaderRoute: typeof AppHotlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expansion': {
      id: '/app/expansion'
      path: '/expansion'
      fullPath: '/app/expansion'
      preLoaderRoute: typeof AppExpansionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creators': {
      id: '/app/creators'
      path: '/creators'
      fullPath: '/app/creators'
      preLoaderRoute: typeof AppCreatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/affiliate': {
      id: '/app/affiliate'
      path: '/affiliate'
      fullPath: '/app/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/creators/$id': {
      id: '/app/creators/$id'
      path: '/$id'
      fullPath: '/app/creators/$id'
      preLoaderRoute: typeof AppCreatorsIdRouteImport
      parentRoute: typeof AppCreatorsRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppCreatorsRouteChildren {
  AppCreatorsIdRoute: typeof AppCreatorsIdRoute
}

const AppCreatorsRouteChildren: AppCreatorsRouteChildren = {
  AppCreatorsIdRoute: AppCreatorsIdRoute,
}

const AppCreatorsRouteWithChildren = AppCreatorsRoute._addFileChildren(
  AppCreatorsRouteChildren,
)

interface AppRouteChildren {
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCommunityRoute: typeof AppCommunityRoute
  AppCreatorsRoute: typeof AppCreatorsRouteWithChildren
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppExpansionRoute: typeof AppExpansionRoute
  AppHotlistRoute: typeof AppHotlistRoute
  AppOutreachRoute: typeof AppOutreachRoute
  AppPlatformsRoute: typeof AppPlatformsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffiliateRoute: AppAffiliateRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCommunityRoute: AppCommunityRoute,
  AppCreatorsRoute: AppCreatorsRouteWithChildren,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppExpansionRoute: AppExpansionRoute,
  AppHotlistRoute: AppHotlistRoute,
  AppOutreachRoute: AppOutreachRoute,
  AppPlatformsRoute: AppPlatformsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
